apiVersion: v1
kind: Pod
metadata:
  name: nginx-seccomp
  annotations:
    # seccomp.security.alpha.kubernetes.io/pod: unconfined # runtime/default
    container.seccomp.security.alpha.kubernetes.io/nginx: unconfined # runtime/default
  labels:
    app: nginx-seccomp
spec:
  containers:
  - name: nginx
    image: nginx
